# Generated by Django 5.1.7 on 2025-03-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='occasion',
            field=models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('school', 'В школу'), ('no_reason', 'Без повода'), ('other', 'Другой повод')], max_length=255, verbose_name='Повод'),
        ),
    ]
