# Generated by Django 5.1.7 on 2025-03-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_consultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquet",
            name="essence_bouquet",
            field=models.TextField(
                blank=True, default="Нет заметок", verbose_name="Смысл букета"
            ),
        ),
    ]
